### ISSUE TITLE
Error: module "sync-it/LocalForage" not found

### ISSUE THREAD

**Issue by felipemartim** [forbesmyester/SyncItBootstrap#3]
Hi!
I got this error when trying to launch the server.

Error: module "sync-it/LocalForage" not found from "/home/felipe/kworkspace/SyncItBootstrap/public/js/SyncItFactory.js"

Updating sync-it version to 0.11.3 in package.json fixed it for me.

**Comment by forbesmyester** [comment]
Thanks for the interest in SyncIt and the report, will look at it over the
weekend.

**Comment by forbesmyester** [comment]
Fixed, thanks for the report.
